name: Format
on: [push]

jobs:
  check:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v2
      - name: checkout unity-meta
        uses: actions/checkout@v2
        with:
          repository: 'unity/unity-meta'
          ref: stable
          path: unity-meta
          lfs: true
          token: ${{ secrets.ALT_GITHUB_TOKEN }}
      - run: mv unity-meta ~/unity-meta
      - run: perl ~/unity-meta/Tools/Format/format.pl --dry-run --nobackups .
